FROM node:20-bullseye

RUN apt-get update && apt-get install -y \
    freecad \
    python3 \
    python3-pip \
    xvfb \
    && pip3 install trimesh \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

CMD ["npm", "run", "worker"]