[phases.setup]
nixPkgs = ["nodejs", "python3", "freecad"]

[phases.install]
cmds = ["npm install", "python3 -m pip install trimesh --break-system-packages"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
