[phases.setup]
nixPkgs = ["nodejs"]
aptPkgs = ["freecad", "python3-pip"]

[phases.install]
cmds = ["npm install", "/usr/bin/python3 -m pip install trimesh --break-system-packages"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
